language: php

php:
  - '8.1'

services:
  - mysql

before_install:
  - cp .env.example .env
  - mysql -e 'CREATE DATABASE efic;'

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit
