language: php

php:
  - 8.2  # Choose the PHP version you want to use for testing

services:
  - mysql  # You can use other databases like PostgreSQL or SQLite if needed

before_install:
  - cp .env.example .env
  - mysql -e 'CREATE DATABASE efic;'

install:
  - composer install --no-interaction

before_script:
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit  # Run PHPUnit tests

